#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" metadata.py

Variables related to the design of the reading passages
"""
__author__ = 'Scott Burns <scott.s.burns@vanderbilt.edu>'
__copyright__ = 'Copyright 2012 Vanderbilt University. All Rights Reserved'

MANIP = {
    1: ['sap', 'hab', 'wbf', 'igloos'],
    2: ['sap', 'hab', 'wbf', 'bugs'],
    3: ['sap', 'mustang', 'wbf', 'bugs'],
    4: ['sap', 'mustang', 'wbf', 'bugs'],
    5: ['sap', 'mustang', 'moths', 'bugs'],
    6: ['octopuses', 'mustang', 'moths', 'bugs'],
    7: ['octopuses', 'mustang', 'moths', 'igloos'],
    8: ['octopuses', 'hab', 'moths', 'igloos'],
    9: ['octopuses', 'hab', 'moths', 'igloos'],
    10: ['octopuses', 'hab', 'wbf', 'igloos']}

BASE = {
    1: ['toads', 'octopuses', 'mustang', 'moths', 'bugs', 'deserts'],
    2: ['toads', 'octopuses', 'mustang', 'moths', 'igloos', 'deserts'],
    3: ['toads', 'octopuses', 'hab', 'moths', 'igloos', 'deserts'],
    4: ['toads', 'octopuses', 'hab', 'moths', 'igloos', 'deserts'],
    5: ['toads', 'octopuses', 'hab', 'wbf', 'igloos', 'deserts'],
    6: ['toads', 'sap', 'hab', 'wbf', 'igloos', 'deserts'],
    7: ['toads', 'sap', 'hab', 'wbf', 'bugs', 'deserts'],
    8: ['toads', 'sap', 'mustang', 'wbf', 'bugs', 'deserts'],
    9: ['toads', 'sap', 'mustang', 'wbf', 'bugs', 'deserts'],
    10: ['toads', 'sap', 'mustang', 'moths', 'bugs', 'deserts']}


NEAR = {
    1: 'scabs',
    2: 'scabs',
    3: 'scabs',
    4: 'crocs',
    5: 'crocs',
    6: 'crocs',
    7: 'crocs',
    8: 'crocs',
    9: 'scabs',
    10: 'scabs'}

FAR = {
    1: 'crocs',
    2: 'crocs',
    3: 'crocs',
    4: 'scabs',
    5: 'scabs',
    6: 'scabs',
    7: 'scabs',
    8: 'scabs',
    9: 'crocs',
    10: 'crocs'}

TOTWORDS = {1: {'toads_baseline_sec':       304,
                'sap_baseline_sec':         308,
                'octopuses_baseline_sec':   302,
                'octopuses_vocab_sec':      302,
                'scabs_near_sec':           304,
                'scabs_far_sec':            304,
                'mustang_baseline_sec':        305,
                'mustang_cohesion_sec':        305,
                'hab_baseline_sec':         303,
                'hab_cohesion_sec':         303,
                'moths_baseline_sec':       301,
                'moths_decode_sec':         301,
                'wbf_baseline_sec':         305,
                'wbf_decode_sec':           305,
                'crocs_near_sec':           292,
                'crocs_far_sec':            292,
                'igloos_baseline_sec':      309,
                'igloos_syntax_sec':        309,
                'bugs_baseline_sec':        307,
                'bugs_syntax_sec':          307,
                'deserts_baseline_sec':     303},
            2: {'toads_baseline_sec':       303,
                'sap_baseline_sec':         308,
                'sap_vocab_sec':            308,
                'octopuses_baseline_sec':   301,
                'octopuses_vocab_sec':      302,
                'scabs_near_sec':           306,
                'scabs_far_sec':            306,
                'mustang_baseline_sec':        305,
                'mustang_cohesion_sec':        301,
                'hab_baseline_sec':         304,
                'hab_cohesion_sec':         303,
                'moths_baseline_sec':       301,
                'moths_decode_sec':         300,
                'wbf_baseline_sec':         306,
                'wbf_decode_sec':           307,
                'crocs_near_sec':           297,
                'crocs_far_sec':            299,
                'igloos_baseline_sec':      309,
                'igloos_syntax_sec':        309,
                'bugs_baseline_sec':        307,
                'bugs_syntax_sec':          316,
                'deserts_baseline_sec':     303},
            3: {'toads_baseline_sec':       303,
                'sap_baseline_sec':         308,
                'sap_vocab_sec':            308,
                'octopuses_baseline_sec':   301,
                'octopuses_vocab_sec':      302,
                'scabs_near_sec':           306,
                'scabs_far_sec':            306,
                'mustang_baseline_sec':        305,
                'mustang_cohesion_sec':        301,
                'hab_baseline_sec':         304,
                'hab_cohesion_sec':         303,
                'moths_baseline_sec':       301,
                'moths_decode_sec':         300,
                'wbf_baseline_sec':         306,
                'wbf_decode_sec':           307,
                'crocs_near_sec':           298,
                'crocs_far_sec':            299,
                'igloos_baseline_sec':      309,
                'igloos_syntax_sec':        309,
                'bugs_baseline_sec':        307,
                'bugs_syntax_sec':          316,
                'deserts_baseline_sec':     303},
            4: {'toads_baseline_sec':       303,
                'sap_baseline_sec':         307,
                'sap_vocab_sec':            307,
                'octopuses_baseline_sec':   306,
                'octopuses_vocab_sec':      306,
                'scabs_near_sec':           310,
                'scabs_far_sec':            310,
                'mustang_baseline_sec':        308,
                'mustang_cohesion_sec':        303,
                'hab_baseline_sec':         307,
                'hab_cohesion_sec':         304,
                'moths_baseline_sec':       307,
                'moths_decode_sec':         307,
                'wbf_baseline_sec':         306,
                'wbf_decode_sec':           305,
                'crocs_near_sec':           302,
                'crocs_far_sec':            302,
                'igloos_baseline_sec':      307,
                'igloos_syntax_sec':        306,
                'bugs_baseline_sec':        310,
                'bugs_syntax_sec':          315,
                'deserts_baseline_sec':     305},
            5: {'toads_baseline_sec':       303,
                'sap_baseline_sec':         307,
                'sap_vocab_sec':            308,
                'octopuses_baseline_sec':   319,
                'octopuses_vocab_sec':      308,
                'scabs_near_sec':           310,
                'scabs_far_sec':            310,
                'mustang_baseline_sec':        319,
                'mustang_cohesion_sec':        304,
                'hab_baseline_sec':         318,
                'hab_cohesion_sec':         303,
                'moths_baseline_sec':       305,
                'moths_decode_sec':         308,
                'wbf_baseline_sec':         306,
                'wbf_decode_sec':           305,
                'crocs_near_sec':           305,
                'crocs_far_sec':            305,
                'igloos_baseline_sec':      308,
                'igloos_syntax_sec':        316,
                'bugs_baseline_sec':        310,
                'bugs_syntax_sec':          315,
                'deserts_baseline_sec':     305},
            }

MANIP_TYPE = {'sap': 'vocab',
              'octopuses': 'vocab',
              'mustang': 'cohesion',
              'hab': 'cohesion',
              'moths': 'decode',
              'wbf': 'decode',
              'igloos': 'syntax',
              'bugs': 'syntax'}

# This maps group letters to values in REDCap
G2RC = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8,
    'J': 9}
